# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('callsign', models.TextField()),
                ('year', models.IntegerField()),
                ('mode', models.TextField()),
            ],
        ),
    ]
