# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestAnalyzerOnline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest',
            new_name='ContestForm',
        ),
    ]
