# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestAnalyzerOnline', '0009_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=300),
        ),
    ]
