# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-21 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestAnalyzerOnline', '0002_auto_20170921_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestForm',
            new_name='ContestInformation',
        ),
    ]
