# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-15 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestAnalyzerOnline', '0006_auto_20171015_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
